import { VideoList } from "@/components/VideoList";
import { VideoProvider } from "@/providers/VideoProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <VideoProvider>
          <div style={{ display: "flex", gap: 16 }}>
            <VideoList />
            <div style={{ display: "flex", flex: "1" }}>{children}</div>
          </div>
        </VideoProvider>
      </body>
    </html>
  );
}
